CREATE DATABASE IF NOT EXISTS bank_test;
USE bank_test;

CREATE TABLE IF NOT EXISTS accounts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    owner VARCHAR(80) NOT NULL,
    balance DECIMAL(12,2) NOT NULL DEFAULT 0
);
